### ISSUE TITLE
Error window is not defined

### ISSUE THREAD

**Issue by GabrielGMartinsBr** [saebekassebil/microphone-stream#1]
I don't know if am i doing it right, but i`m getting the following erro when i try to run the code that are on description page:

/home/gabrielgmartins/node_modules/microphone-stream/index.js:29
  var context = new window.AudioContext;
                    ^
ReferenceError: window is not defined
    at micstream (/home/gabrielgmartins/node_modules/microphone-stream/index.js:29:21)
    at /home/gabrielgmartins/Área de Trabalho/Sign/Labs/Web/NodeJs/Exp/MicrophoneStream/main.js:7:3
    at module.exports (/home/gabrielgmartins/node_modules/getusermedia/index-node.js:13:12)
    at Object.<anonymous> (/home/gabrielgmartins/Área de Trabalho/Sign/Labs/Web/NodeJs/Exp/MicrophoneStream/main.js:6:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
gabrielgmartins@gabrielgmartins-POSITIVO-MOBILE:~/Área de Trabalho/Sign/Labs/Web

**Comment by saebekassebil** [comment]
Looks like you're trying to run this in a _NOT_ browser context. As for now, only browsers are supported. This should be more clear in the README I know, but I haven't really found the time :)

**Comment by GabrielGMartinsBr** [comment]
And how can I run it on web context?
`require` is not supported by my browser i think so, sorry to ask, i have no much experience on node js yet.

**Comment by saebekassebil** [comment]
That's alright. You should take a look at the "browserify" tool. Its a tool that takes your node-code require and all, and bundles it for the browser.

**Comment by saebekassebil** [comment]
This is not really a bug that can be fixed - so I'll close. Hope you figured it out @ GabrielGMartinsBr, otherwise feel free to write here :)
