### ISSUE TITLE
Polyfills for node modules required when using Webpack 5

### ISSUE THREAD

**Issue by sprobst** [saebekassebil/microphone-stream#75]
## Describe the issue with documentation
When using Webpack 5, microphone-stream does not run out-of-the box. When following the integration, the browser will complain about unresolved modules like "Buffer" or "Process". 
After some research I found out that Webpack 5 removed polyfills for node modules and the user now needs to supply them somehow. For me it helped adding the Webpack plugin "node-polyfill-webpack-plugin". It might be worthwhile, putting that into the documentation.

## Steps to reproduce
1. Create a new Vue3 app with CLI or new create-react-app 
2. Add microphone-stream lib
3. Integrate as described
4. Run in browser with Dev Tools open

#### Observed behavior
An Unresolved Module Exception is throw.

#### Expected behavior
It works without any  exceptions

## Additional context
This isn't a bug per se, but it might help to add this detail to the documentation.

**Comment by nfriedly** [comment]
Yeah, that sounds reasonable. Would you like to update the readme and open a pull request?

**Comment by mib008** [comment]
Reason: https://webpack.js.org/configuration/node/

I resolved this problem by using: "webpack": "^5.65.0",

I think it‘s no need to add all Node API from node-polyfill. 
Install buffer, base64-js, readable-stream and process by npm,
then, config “resolve.fallback” and “plugins” properties in webpack config:

```javascript
module.exports = {
  resolve: {
      fallback: {
          'readable-stream': require.resolve('readable-stream'),
          'base64-js': require.resolve('base64-js'),
          buffer: require.resolve('buffer'),
      },
  },
  plugins:[
    new webpack.DefinePlugin({
        'process.browser': JSON.stringify(true),
        'process.env': {
            NODE_ENV: JSON.stringify(process.env.NODE_ENV),
        },
    }),
    new webpack.ProvidePlugin({
        process: 'process/browser',
    }),
  ]
}
```

**Comment by erikh2000** [comment]
I appreciate the two solutions above. The trouble is that either solution requires editing the webpack config file to specify the fallbacks. And in create-react-app the webpack config file is part of react-scripts. That leaves me with some bad options:
OPTION 1 - edit webpack config file where it is stored under node-modules. And do it every time I update react-scripts since that will overwrite it.
OPTION 2 - eject create-react-app and edit webpack config file. Then I won't be able to update react-scripts.
OPTION 3 - might be able to use this thing to override configs. Feels hacky. - https://github.com/gsoft-inc/craco 

What about importing buffer, base64-js, readable-stream, and process directly into microphone-stream so that a polyfill is not needed? If that seems like a reasonable approach, I could try putting together a PR for it.

**Comment by nfriedly** [comment]
@erikh2000 yeah, go ahead and make a PR.

FWIW, you won't need `process` as we eliminated that dependency in #61 and we already import `readable-stream`.

Also, you can probably drop `buffer-from` if you're explicitly importing a version of buffer that we know has `Buffer.from()` support.

I'm not sure about `base64-js`. 

When you make the changes, can you add a new test suite so that it does both the current thing _and_ some tests with webpack? It doesn't have to be as thorough, just something that verifies the library can be used with webpack 5.

**Comment by erikh2000** [comment]
Hmm. It seems like the`readable-stream` is where the reference to `buffer` is. [(Github issue)](https://github.com/nodejs/readable-stream/issues/448) And there's a [blocked PR](https://github.com/feross/safe-buffer/pull/33) to fix it over there. You're already at the latest (v3.6.0) of `readable-stream`.

The change I was hoping to make relied on the references being inside `microphone-stream` unfortunately.

**Comment by erikh2000** [comment]
Or maybe the reference is another level deeper in `safe-buffer`. Anyhow, transitive dependencies - such a mixed blessing. :)

**Comment by nfriedly** [comment]
If there's an alternative to readable-stream that has the same API but plays nicer with webpack 5, we could give it a shot. But I'm not sure if that exists.

**Comment by AuboIoT** [comment]
**Why this error happened?**

- Webpack versions < 5 used to include NodeJS polyfills by default.

- The current version of Webpack no longer includes NodeJS polyfills by default.

- If you use the latests versions of **create-react-app** it will use the latest version of webpack, this causes isues to build applications that use some node methods like process, buffer, etc., many web3 projects also faced this problem (alchemyweb3.js and web3.js).

I used this tutorial and helped me. It's basically the use of the **create-app-rewired** npm module.
https://www.alchemy.com/blog/how-to-polyfill-node-core-modules-in-webpack-5

**Comment by nfriedly** [comment]
I've been banging my head into this problem intermittently. It's harder than it appears; there are some incompatibilities between TypeScript, ES6, ESM, and the various modules we depend on.

https://github.com/microphone-stream/microphone-stream/pull/98 was my failed attempt from a few weeks back.

This morning I tried using https://www.npmjs.com/package/@open-wc/karma-esm?activeTab=code but it hits errors trying to find the transpiled JS files; I think it probably wasn't designed to work with TypeScript. At any rate, it doesn't appear to be supported any more. 

I may end up ripping out Karma and replacing it with something else.

If anyone else thinks they can get it working (with Karma or some other test runner), feel free.

**Comment by Rica02** [comment]
I'm having this issue when trying to use [AWS SDK's transcribe-streaming-app example](https://github.com/awsdocs/aws-doc-sdk-examples/tree/main/javascriptv3/example_code/cross-services/transcribe-streaming-app), which uses `microphone-stream 6.0.1`, into a CRA project using TypeScript and Webpack 5. 

Is there any workaround for this?

**Comment by nfriedly** [comment]
https://stackoverflow.com/questions/64557638/how-to-polyfill-node-core-modules-in-webpack-5 has several answers that might be good short-term solutions for this issue.

**Comment by gwhizoftv** [comment]
HI I'm hitting this too.I'm using React and Vite instead of Webpack. I tried installing readable-stream, buffer,microphone-stream, process and rollup-plugin-noe-polyfills, and making my own nextTick polyfill...
and getting these errors:

[Deprecation] The ScriptProcessorNode is deprecated. Use AudioWorkletNode instead. (https://bit.ly/audio-worklet)

_stream_readable.js:811 Uncaught TypeError: Cannot read properties of undefined (reading 'read')
    at nReadingNextTick (_stream_readable.js:811:8)
_stream_readable.js:494 Uncaught TypeError: Cannot read properties of undefined (reading '_readableState')
    at emitReadable_ (_stream_readable.js:494:22)
_stream_readable.js:547 Uncaught TypeError: Cannot read properties of undefined (reading 'reading')
    at maybeReadMore_ (_stream_readable.js:547:17)
destroy.js:57 Uncaught TypeError: Cannot read properties of undefined (reading '_writableState')
    at emitCloseNT (destroy.js:57:12)
